New Emoji's Added 😄
tyffical/Pridebot pull request #115
Opened 2021-08-11 15:44 UTC by adityamangal1

Blahaj new emoji's

2021-08-19 11:45 UTC, qwe123coder approved these changes
LGTM

2021-08-19 11:46 UTC, qwe123coder commented
and change it forme main to dev branch pls

2022-01-07 07:23 UTC, riconghost commented
Why is this PR pending ? @neeltron @tyffical

2022-01-07 13:44 UTC, tyffical commented
> Why is this PR pending ? @neeltron @tyffical 

'blahajcrying' is not an actual emote in blahajgang server

2022-01-07 13:45 UTC, tyffical requested changes
'blahajcrying' is not an emote on the server. why did u change it from 'blahajcry'?

2022-01-07 13:45 UTC, tyffical commented on main.py
> +            'cry': [custom_map["blahacrying"], custom_map["crii"]],
'blahajcrying' does not exist

2022-01-07 13:45 UTC, tyffical commented on main.py
> +            'alone': [custom_map["blahacrying"]],
'blahajcrying' does not exist

2022-01-07 13:47 UTC, riconghost commented
> 'blahajcrying' is not an emote on the server. why did u change it from 'blahajcry'?

i didnt change anything in the code

2022-01-09 03:16 UTC, tyffical commented
Found the error, "blahajcrying" was misspelled on the server. U should change the code to that spelling as well if youd like to keep these reactions

2022-01-09 03:49 UTC, adityamangal1 commented
> Found the error, "blahajcrying" was misspelled on the server. U should change the code to that spelling as well if youd like to keep these reactions

Will do

2022-01-09 04:40 UTC, tyffical approved these changes
Looks good to me!

2022-01-09 04:40 UTC, merged