feat: WHEREISMYBLAHAJ
tyffical/Pridebot pull request #118
Opened 2021-10-04 05:43 UTC by TheVikJ

A command which sends back a picture of Ryan and 19 Blahajs. We thought of this command like months ago but I got really busy and forgot. Then the whole discord.py fiasco happened and shit went down.

Anyways, after 7 years, I finally bring WHEREISMYBLAHAJ.

2021-10-04 15:18 UTC, tyffical requested changes

2021-10-04 15:18 UTC, tyffical commented on cogs/fun.py
> +    @cog_ext.cog_slash(name="whereismyblahaj", description="find your blahaj (great ad for a dating site)")
-fix description grammar
-you need to add the options parameter to include a recipient; see the hug command

2021-10-04 15:42 UTC, TheVikJ commented on cogs/fun.py
> +    @cog_ext.cog_slash(name="whereismyblahaj", description="find your blahaj (great ad for a dating site)")
I checked the docs before writing the description (I haven't worked with this new library that much) and I checked the previous commands, as well, but I don't know why the description grammar is wrong. Isn't it anyways description=""?

Also for the options parameter, isn't that only for when you want the bot to tag someone? I thought the command was "where is **my** blahaj" so there wouldn't be a recipient apart from the user of the command, so I've used the author's ID now.

2021-10-04 15:45 UTC, tyffical commented on cogs/fun.py
> +    @cog_ext.cog_slash(name="whereismyblahaj", description="find your blahaj (great ad for a dating site)")
-oh i meant the grammar in the description string lol "find yo ur blahaj" -> not sure what you're trying to say here
-ohhhh you're just mentioning the author, that makes sense. good that you changed it to the author's id

2021-10-04 15:45 UTC, tyffical requested changes
see my reply

2021-10-05 03:37 UTC, tyffical approved these changes

2021-10-05 09:05 UTC, neeltron approved these changes

2021-10-05 09:05 UTC, merged