added  /contribute
tyffical/Pridebot pull request #40
Opened 2021-07-16 15:20 UTC by qwe123coder

2021-07-17 05:08 UTC, qwe123coder commented
it gives you a link to contribute

2021-07-17 05:15 UTC, nishant0078 commented
Check the formatting @qwe123coder ok

2021-07-17 05:49 UTC, qwe123coder commented
`    #todo add a dm message with the tree structure of this repo
        #@client.event
        #async def on_message(message):
            #print(message.author.id)` i know it i was the one who indented it in

2021-07-17 05:57 UTC, qwe123coder commented
i aslo removed it

2021-07-23 14:37 UTC, tyffical commented on main.py
> +    #todo add a dm message with the tree structure of this repo
What does this mean?

2021-07-23 14:37 UTC, tyffical commented on main.py
> +from discord_import SlashCommand
Dont change this line

2021-07-23 14:37 UTC, tyffical commented on main.py
> +    url = "https://github.com/tyffical/Pridebot  Hi! Here's the link to the repo to contribute to pride bot! Hope you make me better!"
Just keep the url by itself please, people know what contribute means

2021-07-23 14:45 UTC, tyffical requested changes
See my previous feedback.

2021-07-23 15:04 UTC, qwe123coder commented on main.py
> +    #todo add a dm message with the tree structure of this repo
so it will send a dm to you with a file structure this is a file structure ```
File Structures is the Organization of Data in Secondary Storage Device in such a way that minimize the access time and the storage space. A File Structure is a combination of representations for data in files and of operations for accessing the data. A File Structure allows applications to read, write and modify data.```

2021-07-23 15:20 UTC, tyffical commented on main.py
> +    #todo add a dm message with the tree structure of this repo
I know what a file structure is, is it necessary?

2021-07-23 15:21 UTC, tyffical requested changes

2021-07-23 15:21 UTC, tyffical commented on main.py
> +    url = "https://github.com/tyffical/Pridebot Here's the link to the repo to contribute to pride bot!"
Like i said, just keel the actual url part please

2021-07-23 15:22 UTC, qwe123coder commented on main.py
> +    url = "https://github.com/tyffical/Pridebot  Hi! Here's the link to the repo to contribute to pride bot! Hope you make me better!"
i just kept Here's the link to the repo to contribute to the pride bot!

2021-07-23 15:28 UTC, tyffical approved these changes

2021-07-23 15:28 UTC, merged