Update main.py added /arrest
tyffical/Pridebot pull request #41
Opened 2021-07-17 05:54 UTC by qwe123coder

i forgot to remove arrest pls remove it

2021-07-23 14:44 UTC, tyffical requested changes
As I told you on Discord, please resolve all the grammatical errors.

2021-07-23 14:44 UTC, tyffical commented on main.py
> +from discord_import SlashCommand
Again, don't change this line

2021-07-23 14:44 UTC, tyffical commented on main.py
> +        await ctx.send(content="To whom should I arrest?")
Should be "Whom should I arrest?"

2021-07-23 14:44 UTC, tyffical commented on main.py
> +            content="<@{mention}>, you got arrested \n reason: {reason}".format(
Should be "You're under arrest!"

2021-07-23 14:44 UTC, tyffical commented on main.py
> +            content="<@{mention}>, you got arrested \n reason: {reason}".format(
Use the same if if elif else structure that the old arrest command used.

2021-07-23 14:44 UTC, tyffical commented on main.py
> +          description="Why are you arrest blahajganger ?",
Should be "Why should they be arrested?"

2021-07-24 04:29 UTC, qwe123coder commented on main.py
> +            content="<@{mention}>, you got arrested \n reason: {reason}".format(
@tyffical i used this as the one you had was giving some bugs so i mad my one it work just fine as the old one
the old code even when i gave whom and why 

old code 
![image](https://user-images.githubusercontent.com/72848513/126857286-e2c438ef-8f8c-4d2a-9581-a65f3015bb79.png)


new code 

![image](https://user-images.githubusercontent.com/72848513/126857317-36a551d3-5a86-4094-a658-3a1fbc1d97c8.png)

2021-07-24 04:37 UTC, tyffical requested changes

2021-07-24 04:37 UTC, tyffical commented on main.py
> +          description="Who do you want to arrest ?",
Change to whom

2021-07-24 04:46 UTC, qwe123coder commented on main.py
> +            content="<@{mention}>, you got arrested \n reason: {reason}".format(
> Use the same if if elif else structure that the old arrest command used.

it dose not work

2021-07-24 04:50 UTC, tyffical requested changes

2021-07-24 04:50 UTC, tyffical commented on main.py
> +        reason = "yeet just for fun! :"
Missing ) for smiley face :)

2021-07-24 04:50 UTC, tyffical commented on main.py
> +          description="Whom do you want to arrest ?",
Delete the weird space before the ?

2021-07-24 04:54 UTC, qwe123coder commented on main.py
> +        reason = "yeet just for fun! :"
fixed

2021-07-24 04:55 UTC, qwe123coder commented on main.py
> +          description="Whom do you want to arrest ?",
fixed

2021-07-24 05:12 UTC, tyffical approved these changes

2021-07-24 13:58 UTC, nishant0078 reviewed
![Screenshot from 2021-07-24 19-27-23](https://user-images.githubusercontent.com/16706263/126870710-ee917782-9d87-44ae-b0f5-f153ac90953b.png)


Please correct the formatting here

2021-07-24 15:30 UTC, qwe123coder commented
@nishant0078 i did not get you can you tell what line i messed up

2021-07-24 15:31 UTC, nishant0078 commented
Look at the Image it is attached the indentation is wrong all over the place

2021-07-24 15:34 UTC, qwe123coder commented
this 
![image](https://user-images.githubusercontent.com/72848513/126873441-65dd79dd-f8a7-4842-9897-97c557cd63b4.png)
? 
if yess it still works fine

2021-07-24 15:49 UTC, nishant0078 commented
Alright Code is good to go. Hope you have fixed all the grammar error

2021-07-24 16:23 UTC, tyffical commented
It looks alright, but there are merge conflicts with main branch that need to be fixed

2021-07-24 16:24 UTC, tyffical requested changes
Pull from main branch and fix merge conflicts

2021-07-24 23:32 UTC, merged