/colors added
tyffical/Pridebot pull request #51
Opened 2021-07-27 05:47 UTC by qwe123coder

2021-07-28 20:32 UTC, tyffical requested changes

2021-07-28 20:32 UTC, tyffical commented on main.py
> +@slash.slash(name="colors", guild_ids=guild_ids, description="gift a pride!",
a pride flag*

2021-07-29 03:49 UTC, qwe123coder commented on main.py
> +@slash.slash(name="colors", guild_ids=guild_ids, description="gift a pride!",
done

2021-07-29 04:21 UTC, tyffical requested changes

2021-07-29 04:21 UTC, tyffical commented on main.py
> +@slash.slash(name="colors", guild_ids=guild_ids, description="a pride flag",
please work on your reading comprehension haha

i meant, u just needed to add flag to the end of the description

so, to be exact: description="gift a pride flag!"

2021-07-30 20:29 UTC, tyffical approved these changes

2021-07-30 20:29 UTC, merged